groups:
  - name: rabbitmq_alerts
    rules:
      - alert: RabbitMQDown
        expr: rabbitmq_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ недоступен"
          description: "{{ $labels.instance }}: RabbitMQ недоступен более 1 минуты."
