global:
  scrape_interval: 15s      # Более разумный интервал для продакшена
  evaluation_interval: 15s  # Проверка алертов раз в 15 секунд

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]
        labels:
          app: 'service-registry'

#  # 3. Пример для других Spring-приложений на localhost
#  - job_name: 'user-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'host.docker.internal:8080' ]  # user-service на порту 8080
#        labels:
#          app: 'user-service'